modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="beyond_planets_core"
version="${file.jarVersion}"
displayName="Beyond Planets Core"
credits="TheRealM18"
authors="TheRealM18"
description='''
This mod for the core of Beyond Planets.
'''

[[dependencies.beyond_planets_core]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_planets_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_planets_core]]
    modId="beyond_earth"
    mandatory=true
    versionRange="[6.1,)"
    ordering="AFTER"
    side="BOTH"