name: Feature Request
labels:
  - enhancement
assignees:
  - Lego245
description: Suggest an improvement or a new feature
body::
  - type: dropdown
    id: modloader
    attributes:
      label: Minecraft version
      options:
        - 1.18.2
        - 1.19
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Any other relevant information, such as the usecase, alternative solutions, etc.
